#!/usr/bin/env python
"""Execute the class‑wise error analysis steps described in class_error_analysis.md.

This script:
1. Loads `outputs/validation_results.csv`.
2. Computes per‑class precision/recall/F1 and saves `outputs/per_class_performance.csv`.
3. Generates three markdown files with high‑confidence mis‑predictions and Grad‑CAM images for the worst classes.
"""

import pandas as pd
from pathlib import Path
from sklearn.metrics import precision_score, recall_score, f1_score

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[1]
RESULTS_CSV = ROOT / "outputs" / "validation_results.csv"
PER_CLASS_CSV = ROOT / "outputs" / "per_class_performance.csv"
ERROR_EXAMPLES_DIR = ROOT / "reports" / "error_examples"
ERROR_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Load validation results
# ---------------------------------------------------------------------------
print(f"Loading validation results from {RESULTS_CSV}")
df = pd.read_csv(RESULTS_CSV)

# ---------------------------------------------------------------------------
# Per‑class metrics
# ---------------------------------------------------------------------------
classes = sorted(df["actual_label"].unique())
metrics = []
for cls in classes:
    cls_df = df[df["actual_label"] == cls]
    precision = precision_score(cls_df["actual_label"], cls_df["predicted_label"], labels=[cls], average="macro", zero_division=0)
    recall = recall_score(cls_df["actual_label"], cls_df["predicted_label"], labels=[cls], average="macro", zero_division=0)
    f1 = f1_score(cls_df["actual_label"], cls_df["predicted_label"], labels=[cls], average="macro", zero_division=0)
    metrics.append({"Class": cls, "Precision": precision, "Recall": recall, "F1": f1, "Support": len(cls_df)})

per_class_df = pd.DataFrame(metrics)
per_class_df.to_csv(PER_CLASS_CSV, index=False)
print(f"Per‑class performance saved to {PER_CLASS_CSV}")
print(per_class_df)

# ---------------------------------------------------------------------------
# High‑confidence wrong predictions for worst classes
# ---------------------------------------------------------------------------
worst_classes = ["Basal Cell Carcinoma", "Dermatofibroma", "Melanoma"]
GRADCAM_DIR = ROOT / "gradcam_outputs"
for cls in worst_classes:
    subset = df[(df["actual_label"] == cls) & (df["predicted_label"] != cls)]
    top_errors = subset.sort_values(by="confidence", ascending=False).head(5)
    md_path = ROOT / "reports" / f"{cls.replace(' ', '_')}_error_examples.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"# {cls} – High‑Confidence Wrong Predictions\n\n")
        f.write("| Image | Predicted | True | Confidence | Grad‑CAM |\n")
        f.write("|-------|-----------|------|------------|----------|\n")
        for _, row in top_errors.iterrows():
            img_path = ROOT / "processed" / "images" / f"{row['image_id']}.jpg"
            dest_img = ERROR_EXAMPLES_DIR / f"{row['image_id']}_orig.jpg"
            if img_path.exists():
                dest_img.write_bytes(img_path.read_bytes())
            # Grad‑CAM overlay (generated by prediction service)
            gradcam_path = GRADCAM_DIR / f"{row['image_id']}_overlay.png"
            gradcam_md = ""
            if gradcam_path.exists():
                gradcam_dest = ERROR_EXAMPLES_DIR / f"{row['image_id']}_gradcam.png"
                gradcam_dest.write_bytes(gradcam_path.read_bytes())
                # Use relative path for markdown
                rel_path = gradcam_dest.relative_to(ROOT)
                gradcam_md = f"![Grad‑CAM]({rel_path})"
            rel_img = dest_img.relative_to(ROOT) if dest_img.exists() else ""
            f.write(f"| ![Img]({rel_img}) | {row['predicted_label']} | {row['actual_label']} | {row['confidence']:.2%} | {gradcam_md} |\n")
    print(f"Created {md_path}")

print("Class‑wise error analysis completed.")
